id = sweepxmobile
name = SweepX عربي
mainURL = https://x.com/home
deeplink = x.com twitter.com
scripts = sweepx-ar.user.js
allowSubdomains = true
requireDoubleBackToExit = true
enableExternalLinks = true
openExternalLinksInBrowser = false
confirmOpenInBrowser = false
allowOpenMobileApp = false
JSEnabled = true
JSCanOpenWindowsAutomatically = true
DomStorageEnabled = true
DatabaseEnabled = true
SavePassword = true
AllowFileAccess = true
AllowFileAccessFromFileURLs = true
edgeToEdge = false
forceDarkTheme = true
cameraEnabled = false
microphoneEnabled = false
geolocationEnabled = false
